### ISSUE TITLE
How to compile mp4v2  against libc++. libstdc++ support deprected for xcode 10.1

### ISSUE THREAD

**Issue by kirubaios** [JQJoe/mp4v2-for-iOS#1]
I used libmp4v2 library for long time. Now I need to build the libmp4v2 in xcode 10. but it shows linker error.How can i compile libmp4v2 against libc++. I tried a lot but i cant get through it.

**Comment by JQJoe** [comment]
if your project structure has libstdc++ included, it might have turned red because Xcode couldn't find the reference for it. If you remove that entry from the project structure and add the new lib instead(libc++), you're good to go.

**Comment by kirubaios** [comment]
Thanks for the reply. I tried all the things but no luck.It works before Xcode 10. In Xcode 10 only I faced this issue. Can you provide me a script to build the library
 against libc++?

**Comment by JQJoe** [comment]
This script may be you need,
Please rebuild and test,
Thank you !

kirubaios <notifications@github.com> 于2019年2月20日周三 下午1:28写道：
